version: "3.8"
services:
  warp-clash:
    build: .
    ports:
      - "41001:3000"
    env_file:
      - .env.local
    volumes:
      - ./config:/app/config
      - ./account:/app/account
      - ./logs:/app/logs
      - /etc/hosts:/etc/hosts:ro
